CREATE PROCEDURE [data].[Populate_dbo_Channel]
AS
BEGIN
/*
	Table's data:    [dbo].[Channel]
	Data Source:     [DEV19].[CRM]
	Created on:      27/04/2019 11:48:58
	Scripted by:     DEV19\Administrator
	Generated by     Data Script Writer - ver. 2.0.0.0
*/
PRINT 'Populating data into [dbo].[Channel]';

IF NOT EXISTS (SELECT TOP (1) * FROM [dbo].[Channel])
BEGIN

	SET IDENTITY_INSERT [dbo].[Channel] ON;

	;WITH cte_data
	as (SELECT [ChannelId], [Label], [Name], [Description] FROM 
	(VALUES
	  (1,	'01',	'Store',	'New Store')
	, (2,	'02',	'Online',	'Online')
	, (3,	'03',	'Catalog',	'Catalog')
	, (4,	'04',	'Reseller',	'Reseller')
	) as v ([ChannelId], [Label], [Name], [Description])
)
	INSERT INTO [dbo].[Channel]
	([ChannelId], [Label], [Name], [Description])
	SELECT [ChannelId], [Label], [Name], [Description]
	FROM cte_data;

	SET IDENTITY_INSERT [dbo].[Channel] OFF;

END

-- End data of table: [dbo].[Channel] --
END
GO
